### ISSUE TITLE
Client information available in project charter [2024/03/25]

### ISSUE THREAD

**Issue by TechXplorerFR** [algosup/2023-2024-project-4-sportshield-team-5#10]
### Description

The client's name is mentioned in the project charter.

### Severity

4. Critical (Severe impact)

### Version

3e67380

### Line 140

Expected:
Replace the client's name with a placeholder or remove it.

**Comment by Bistrel2002** [comment]
ISSUE WITH THE COMPANY'S NAME RESOLVED👍🏽.

**Comment by TechXplorerFR** [comment]
LGTM 👍
