### ISSUE TITLE
Technical: Typos in the document [2024/03/26]

### ISSUE THREAD

**Issue by TechXplorerFR** [algosup/2023-2024-project-4-sportshield-team-5#17]
### Description

Some elements are missing/wrong in the technical `(/documents/technical-specifications/technical-specification.md)` and should be updated as soon as possible.

### Severity

4. Critical (Severe impact)

### Version

a4ad752

### Line 211

Typo

Current:
`The **dev branch** hosts the software we are coding, but requires the code inside to don't have any compilation errors, and, if possible, to work as expected at th current step.`

Expected:
`The **dev branch** hosts the software we are coding, but requires the code inside to don't have any compilation errors, and, if possible, to work as expected at the current step.`

### Lines 261 to 263

Extra possessive and plurals

Current:
```The variables' names are in \`\`\`snake_case\`\`\`.
The functions' names are in `\`\`camelCase\`\`\`.
The definitions' names are in `\`\`COBOL_CASE\`\`\`.```

Expected:
Current:
```The variable names are in \`\`\`snake_case\`\`\`.
The function names are in `\`\`camelCase\`\`\`.
The definition names are in `\`\`COBOL_CASE\`\`\`.```

### Line 267 

Extra preposition

Current:
`The indentation of 2 spaces is added after each carriage return in after a curly bracket.`

Expected:
`The indentation of 2 spaces is added after each carriage return after a curly bracket.`

### Line 277

Wrong verb form

Current:
`If a number or a constant is needed in the code, it have to be defined in the 'definitions.h' header and not directly inserted in the algorithm itself, even if "it shouldn't change".`

Expected:
`If a number or a constant is needed in the code, it has to be defined in the 'definitions.h' header and not directly inserted in the algorithm itself, even if "it shouldn't change".`

### Line 283

Wrong verb form and blurry sentence

Current:
`Each function need a comment above explaining its behavior and how parameters are used.  `

Expected:
`Each function needs a comment above explaining its behaviour and needed parameters along with their type.  `

### Line 285

Wrong verb form

Current:
`Any variable declaration need a comment on the same line to quickly explain what it is. If it is too obvious, just write \`\`\`// explicit\`\`\`.`

Expected:
`Any variable declaration needs a comment on the same line to quickly explain what it is. If it is too obvious, just write \`\`\`// explicit\`\`\`.`

### Line 336

Typo

Current:
`## Headers and defintition.h`

Expected:
`## Headers and definition.h`

### Line 393

Missing uppercase character

Current:
`#### specifications`

Expected:
`#### Specifications`

### Line 405

Wrong verb form

Current:
`Each time we need to get the GPS position we first have to enable the wake up pin of the GPS module : D8, and then turned it off again.`

Expected:
`Each time we need to get the GPS position we first have to enable the wake-up pin of the GPS module: D8, and then turn it off again.`

### Line 407 

Missing uppercase character

Current:
`#### implementation`

Expected:
`#### Implementation`

### Line 419

Wrong word usage

Current:
`As we can see, the maximum voltage (charging voltage) is 4.2V and the voltage can drop down until 2.75V MAXIMUM before its cut-off according to the documentation provided.   `

Expected:
`As we can see, the maximum voltage (charging voltage) is 4.2V and the voltage can drop down until 2.75V MINIMUM before its cut-off according to the documentation provided.   `

### Line 428

Extra uppercase characters

Current:
`WHen we received the project, the current idea was to split a detected movement into 3 categories : noise, small and big movements.`

Expected:
`When we received the project, the current idea was to split a detected movement into 3 categories: noise, small and big movements.`

### Line 431

Wrong word usage & typos

Current: 
`That's why we decided to just differenciate noise and movement, and to look at the duration of the movement more than the intensity. This way, a short shock, wich can happens won't be detected as a theft while any movement lasting more than 1 second is detected as a theft, and in any case, any movement trigger a small alarm for 1 second, as a dissuasion. However the GPRS signal to get a notification on the app will be received only when an real theft is detected.`

Expected:
``` 
This is the reason why we decided to just differentiate noise and movement and to focus on the duration of the movement rather than its intensity. This way, a short shock, which can happen won't be detected as a theft while any movement lasting more than 1 second is detected as one. In any case, any movement triggers a small alarm for 1 second, as a dissuasion to warn the person responsible for this movement.
 
However, the GPRS signal to get a notification on the app will be received only when a real theft is detected, after one second of movement.
```

### Other Details

/

**Comment by Bistrel2002** [comment]
Typos ok

**Comment by TechXplorerFR** [comment]
LGTM 👍
