### ISSUE TITLE
Technical: General comments and corrections [2024/03/26]

### ISSUE THREAD

**Issue by TechXplorerFR** [algosup/2023-2024-project-4-sportshield-team-5#18]
### Description

Some elements are missing/wrong in the technical `(/documents/technical-specifications/technical-specification.md)` and should be updated as soon as possible.

### Severity

4. Critical (Severe impact)

### Version

a4ad752

### Line 271

No approximations in the document & missing comma

Current:
`However some simple statements can be written in one line, as long as it doesn't take more than 50 characters aproximately.`

Expected
`However, some simple statements can be written in one line, as long as it doesn't take more than 50 characters`

### Line 287

Awkward phrasing

Current:
`### Example of a good code*`

Expected:
`### Expected piece of code`

### Line 319

Remove your comment on "this is a non-sense"

### Line 321

Awkward phrasing

Current:
`# 5. Software's technical specifications`

Expected:
`# 5. Software's technical implementation`

### Lines 327 to 334

General rephrasing in the overview section

Current:
```
We don't have access to the application, the server with which the SIM card communicates or the final hardware. And we are not supposed to use our smartphones to test the NFC or the bluetooth.  
That's why the company has explicitly suggested that we only **simulate** the complex interactions with the hardware, such as Bluetooth communication or sending data over the 2G network (soon to be obsolete), by using forced values such as "bluetooth_unlock = 1 or 0 : the user has pressed the button on the application or not".   
The company's request is really to improve the software by finding an effective algorithm, and not to write assembly to make components working. (It is the reason why we only had 4.5 weeks to work on, while it is usally 6 or 7.)
We will therefore focus on technical detail only on the points where we can take action. These are:  
- battery management and energy consumption (sleep mode, power cut, ...)
- multi tasks to make the buzzer ringing and to send the notification at the same time, while also being able to stop the alarm at any moment.
- take the NFC into account
- movement detection (improve the way to detect a theft)
```

Expected:
```
We don't have access to the server with which SportShield communicates, thanks to the SIM card. Additionally, we don't have access to the final hardware as the product is still a prototype.  
The company suggested we should assume we have access to it and could add whatever we want if we want to add additional functions on the server side.
We will therefore focus on the technical details specified in the KPIs given by the client. These are:  
- Battery management and energy consumption (sleep mode, power cut, ...)
- Multi-tasking to make the buzzer ring and send notifications at the same time, while also being able to stop the alarm at any moment.
- Add NFC management to unlock SportShield.
- Improve movement detection to enhance the distinction between an accidental bump in the lock from a real theft attempt.
```

### Lines 338 and 349

Awkward phrasing:

Current:
`In this file there are :`

Expected:
`This file contains:`

### Lines 349 to 354

Enhancement of readability

Current:
```
In this file there are :
- **inclusion** of the different **headers** (and not the libraries -> 'definition.h')
- the '**void setup()**' where are executed only functions.  
  this function contains the code which will be executed once at the beginning after a reload of the program on the board (after a power-up or reset)
- the '**void loop()**'
  this function has the role of a 'while(true)' loop : it is the main loop
```

Expected:
```
This file includes:

- Calls to the different **headers** (*.h/*.hpp files)
- The `void setup()` function: *It contains the code executed once to setup the environment after a startup or a reset of the board.*
- The `void loop()` function: *It contains the code which will be ran during the whole execution of the program. It acts as a while loop.*
```

### Line 380

Rephrase to allow better understanding

Current:
`We don't need to forecast what is in the 'void setup()' function. This is just all the initializations of the different components and libraries, and the setting of what is the initial state of the device.`

Expected:
```
The `void setup()` function is not part of the algorithm itself. Its only purpose is to import the required libraries and headers and describe the program's initial state.
```

### Line 382

**Unacceptable comment in a document!!!**

Current:
`Now, the algorithm itself, the main loop of the firmware, is available in this diagram (please forgive the size !) :`

Expected:
```
This leaves the core of the algorithm, the `void loop()` function. The following diagram describes the expected behaviour of the lock:
```

### Lines 386 to 389

Uniformization among all the bullet points:

Current:
```
It allows :
- the battery consumption's management
- execute parallel tasks when a theft is detected
- to take advantage of the NFC
```

Expected:
```
It allows :
- To manage the battery consumption
- To execute parallel tasks when a theft is detected
- To take advantage of the NFC
```

### Line 400

Approximation in a value

Current:
`If the battery level is ABOVE 15%, NFC only is enabled because NFC consume like 5mA while Bluetooth Low Energy (BLE) consumes 15mA (3 times more).`

Expected:
`If the battery level is ABOVE 15%, NFC only as it is less energy-consuming (5mA) compared to Bluetooth Low Energy (BLE) which consumes 15mA.`

### Line 403

Wrong verb forms

Current:
`If only one of these components are required, we turn on both D4 and D9, and a variable have to keep track of the number of devices currently used. If there is any, D9 and D4 are turned OFF to save as much energy as possible.`

Expected:
`If only one of these components is required, we turn on both pins D4 and D9. Concurrently, a variable has to keep track of the number of devices currently in use. If none is in use, D9 and D4 are turned OFF to save as much energy as possible.`

### Line 409

Missing information of library name

Current: 
`Also, the percentage of the battery and the management of its charge will require a specific public library called...  `

Expected: Add the name of the library involved

### Line 411

Typo and clarification

Current:
`A key feature of the battery management ids the ability to know the current capacity (%). There are 2 methods for that :`

Expected:
`A key feature of battery management is the ability to know the current capacity as a percentage. There are 2 methods to achieve this objective:`

### Line 412

Typo and rephrasing

Current:
`- The ideal one but over-consuming electricity is to measure constantly the voltage and the intensity which goes out from the battery to know how much energy had beeen used or had been loaded in real-time. However it is almost impossible to imlement and this solution using though a 'coulombmeter' is reserved for very particular usages.`

Expected:
`- The ideal but most energy-consuming option is to measure constantly tension and intensity in the battery to know the battery level in real-time. However, in our case, this option is not convenient as it requires a coulombmeter.`

### Line 413

Typo and rephrasing

Current:
`- The very spread solution is to just measure the current voltage and to compare the value to a set of previous measures took to define the correlation between the current capacity and the current voltage.`

Expected:
`- The very spread solution is to just measure the present voltage and to compare the obtained value to a set of previously measured values. We can then correlate values between the maximum and the present voltage to obtain the battery level.`

### Line 422

Typo and total rephrasing

Current:
`Furthermore, as the temperature would be quite low, around 41°F to 23°F (as it is mainly for skis and snowboards), the discharge should avoid to eceed 80% of the total capacity. We finally get a minimum voltage (if the battery is in a cold environement) of 3.4V corresponding to a 0%. Also, we will used some standard curves of discharge to evaluate the current battery capacity based on the voltage we can get from the board itself (included function).`

Expected:
`Furthermore, as the temperature would be quite low, from 41°F to 23°F on average (as this product targets winter sports equipment), the discharge should avoid falling below 20% of the battery level. This limits the risk of the user device reaching the minimum voltage we can get in the battery: 3.4V, corresponding to 0% of charge, meaning the battery cannot be charged again anymore. 
Complementarily, we will use some standard curves of discharge to evaluate the current battery capacity based on the voltage we can get from the board itself.`

### Line 424

Confusing and somewhat useless sentence

### Line 435

Definition after the term which should be in the glossary. This section also lacks multiple information

Current:
`As the buzzer is controlled by a MOSFET, we decided to use PWM (Pulse Wave Modulation = a high frequency square wave, where the proportion of ON/OFF time in average can be set), to make the piezzo-electric buzzer ring lower. A simple R-C circuit would have been better to smooth the output voltage to the buzzer, but as the MOSFET has a capacitance, even if the song is not the same we succeeded to get a lower noise from the buzzer.`

Expected:
`As the buzzer is controlled by a MOSFET, we decided to use PWM[^ref], to make the piezzo-electric buzzer ring lower. A simple R-C circuit would have been better to smooth the output voltage to the buzzer, but as the MOSFET has a capacitance, even if the song is not the same we succeeded in getting a lower noise from the buzzer.`

### Line 439

Sentences need to be shortened and rephrased

Current:
`As the Seeed boards company released their Xiao-NRF52840 quite recently, we found on the official forum of the company website for documentation, that they said they still didn't ended to develop the NFC library of their board. The problem with this unfinished library, is that, as they have their own version of RFID microship and circuit, embedded in the board, the only solution we found to try having it working, is by coding our own library directly in assembly. That's why we probably won't develop the concrete NFC functions more than simulating input and output through the terminal.`

Expected:
`As the Seeed boards' company released their Xiao-NRF52840 quite recently, they still didn't end up developing the NFC library of their board, as said on their forum. This raises a major issue. As they have their proprietary version of the RFID microchip and circuit, the only workaround would be coding our library directly in assembly. That's why we probably won't develop the concrete NFC functions more than simulating input and output through the terminal.`

### Line 442 to 446

Empty sections that might need content addition

Expected: Addition of the missing content

### Other Details

/

**Comment by Bistrel2002** [comment]
Typos OK 👌

**Comment by TechXplorerFR** [comment]
LGTM 👍
