### ISSUE TITLE
MIT License [2024/03/15]

### ISSUE THREAD

**Issue by Biohazardyee** [algosup/2023-2024-project-4-sportshield-team-5#2]
### Description

I noticed that on your GitHub repository, the selected license is the MIT (copyright free). I'm not sure that it is the right license for this project as it is definitely not an open source project. 

### Severity

4. Critical (Severe impact)

**Comment by TechXplorerFR** [comment]
The customer will be contacted shortly to ensure that the chosen license meets his requirements. Thanks for opening this issue.

**Comment by TechXplorerFR** [comment]
This issue can now be closed as the license has been replaced by a BSD-3-Clause license.
