### ISSUE TITLE
Critical Path Corrections [2024/04/06]

### ISSUE THREAD

**Issue by TechXplorerFR** [algosup/2023-2024-project-4-sportshield-team-5#20]
### Description

The Critical path `/documents/management/Critical path.md` includes several errors which need to be addressed as soon as possible.

### Severity

4. Critical (Severe impact)

### Version

b0ba00a

### Line 9

The image shows the wrong dependent tasks, instead, it should look like this:

| Task ID | Task Name                | Predecessors        | Duration |
| ------- | ------------------------ | ------------------- | -------- |
| A       | Project Charter          | /                   | 1 day    |
| B       | Functional Specification | A                   | 3 days   |
| C       | Technical Specification  | A, B                | 6 days   |
| D       | User Manual              | A, B, C             | 20 days  |
| E       | Test Plan                | A, B, C             | 20 days  |
| F       | Prototype Code Review    | A                   | 2 days   |
| G       | Alarm management         | A, B, C, F          | 3 days   |
| H       | NFC & Bluetooth          | A, B, C, F, G       | 6 days   |
| I       | Battery management       | A, B, C, F, G, H    | 4 days   |
| J       | Security Issues          | A, B, C, F, G, H, I | 3 days   |

Additionally, the durations seem quite optimistic. They might need a review to ensure they are correct.

### Line 12

Wrong word usage

Current:
`This is the unique identification of a particular task. It is essential to identify the pattern of dependent and independent tasks.`

Expected:
`This is the unique identifier linked to a particular task. It is essential to identify the pattern of dependent and independent tasks in an easily readable manner.`

### Line 18

Wrong word usage & Global rephrasing

Current:
`Here, we assign the TASK ID to different tasks that require a particular task to be completed before they can start executing. A dash is used to represent tasks that don't depend on any other tasks before starting.`

Expected:
`This field points out the tasks that require previous accomplishments on the project before being started. These accomplishments are represented by the identifiers of tasks in this field. A slash is used to represent tasks that don't depend on any other tasks before starting.`

### Other Details

/

**Comment by Bistrel2002** [comment]
I have reviewed the text and made the necessary corrections. It is now free of errors.👍🏽

**Comment by TechXplorerFR** [comment]
LGTM 👍
